# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    number.to.word:
        class: FadcoBundle\Services\Number2Word

    # To fix You have requested a non-existent service "fos_user.doctrine_registry" error
    fos_user.doctrine_registry:
        alias: doctrine

    smsgo:
        class: SmsGo\SmsGo
        factory: [SmsGo\SmsGoFactory, create]
        arguments: ['@service_container']

    smsgo.sms_logger:
        class: SmsGo\SmsLogger
        arguments: ['@logger']

#    twig.extension.intl:
#        class: Twig_Extensions_Extension_Intl
#        tags:
#            - { name: twig.extension }

    ajaxify_search.routing_loader:
        class: AjaxifySearch\Routing\RouteLoader
        tags:
            - { name: routing.loader }

    ajaxify_search.controller:
        class: AjaxifySearch\AjaxifySearchController
        arguments: ['@doctrine.orm.entity_manager', '@templating']

    ajaxify_search.twig_extension:
        class: AjaxifySearch\AjaxifySearchTwigExtension
        arguments: ['@twig', '@router']
        tags:
            - { name: twig.extension }


    data_table_ajax_controller:
        class: FadcoBundle\Controller\DataTable\DataTable\Ajax\DataTableAjaxController
        arguments: ['@doctrine', '@data_table_ajax_repository', '@templating']

    data_table_ajax_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        public: false
        arguments:
            - "FadcoBundle\Controller\DataTable\DataTable\Ajax\Entity\DataTableAjax"