lc_homepage:
    path:     /lchp
    defaults: { _controller: LCBundle:Default:index }

lc_user_discussions:
    path:     /lcgud
    defaults: { _controller: LCBundle:Default:getLcUserDiscussions }

lc_users:
    path:     /lcgurs
    defaults: { _controller: LCBundle:Default:getLcUsers }
    
lc_users_ajout_contact:
    path:     /lcgursc
    defaults: { _controller: LCBundle:Default:getLcUsersAjoutContact }

lc_creer_nouvelle_discussion:
    path:     /lccnd
    defaults: { _controller: LCBundle:Default:creerNouvelleDiscussion }
    
lc_ajouter_contact_discussion:
    path:     /lcac
    defaults: { _controller: LCBundle:Default:ajouterContact }

lc_discussion_messages:
    path:     /lcdm
    defaults: { _controller: LCBundle:Default:getDiscussionMessages }

lc_creer_nouveau_message:
    path:     /lccnm
    defaults: { _controller: LCBundle:Default:creerNouveauMessage }
    
lc_creer_nouveau_message_image:
    path:     /lccnmi
    defaults: { _controller: LCBundle:Default:creerNouveauMessageImage }
    
lc_creer_nouveau_message_image_contact:
    path:     /lccnmic
    defaults: { _controller: LCBundle:Default:creerNouveauMessageImageContact }

lc_users_nouveaux_messages:
    path:     /lcugnm
    defaults: { _controller: LCBundle:Default:getnouveauxMessages }
    
lc_users_nouveaux_messages_discussion:
    path:     /lcugnmd
    defaults: { _controller: LCBundle:Default:getnouveauxMessagesDiscussion }
    
lc_users_nouveaux_messages_contact:
    path:     /lcugnmc
    defaults: { _controller: LCBundle:Default:getnouveauxMessagesContact }

lc_users_vefification_nouveaux_messages:
    path:     /lcuvnm
    defaults: { _controller: LCBundle:Default:verificationNouveauxMessages }

lc_marquer_lu:
    path:     /lcml
    defaults: { _controller: LCBundle:Default:marquerLu }

lc_discussion_messages_contact:
    path:     /lcdmc
    defaults: { _controller: LCBundle:Default:getDiscussionMessagesContact }
    
lc_creer_nouveau_message_contact:
    path:     /lccnmc
    defaults: { _controller: LCBundle:Default:creerNouveauMessageContact }
    
lc_marquer_lu_contact:
    path:     /lcmlc
    defaults: { _controller: LCBundle:Default:marquerLuContact }
    
lc_register: 
    path:     /lcr
    defaults: { _controller: LCBundle:Default:lcRegister }

lc_gcu:
    path:     /lcgcu
    defaults: { _controller: LCBundle:Default:lcGetConnectedUser }
    
lc_creer_nouveau_message_fichier:
    path:     /lccnmf
    defaults: { _controller: LCBundle:Default:creerNouveauMessageFichier }
    
lc_creer_nouveau_message_fichier_contact:
    path:     /lccnmfc
    defaults: { _controller: LCBundle:Default:creerNouveauMessageFichierContact }
    
lc_newindex:
    path:     /lci
    defaults: { _controller: LCBundle:Default:newindex }