services:

    lc.chat:
        class: LCBundle\Service\WsocketService
        tags:
            - { name: gos_web_socket.topic }
        arguments: ["@service_container"]
    
    lc.cd:
        class: LCBundle\Service\WcdService
        tags:
            - { name: gos_web_socket.topic }