<?php

namespace FadcoBundle\Entity;

/**
 * CompteDistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteDistributeurRepository extends \Doctrine\ORM\EntityRepository
{
}
