LCBundle\Entity\LcUser:
    type: entity
    repositoryClass: LCBundle\Entity\LcUserRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idoriginal:
            type: bigint
        derniereconnexion:
            type: datetime
        nom:
            type: text
        prenom:
            type: text

    manyToMany:
        discussions:
            targetEntity: LcDiscussion
            mappedBy: intervenants

    lifecycleCallbacks: {  }
