<?php

namespace FadcoBundle\Repository;

/**
 * AlerteSmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteSmsRepository extends \Doctrine\ORM\EntityRepository
{
}
