<?php

namespace FadcoBundle\Repository;

/**
 * ComplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplementRepository extends \Doctrine\ORM\EntityRepository
{
}
