<?php

namespace FadcoBundle\Repository;

/**
 * MailsEnvoyesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailsEnvoyesRepository extends \Doctrine\ORM\EntityRepository
{
}
