<?php

namespace FadcoBundle\Repository;

use FadcoBundle\Entity\Piece;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends \Doctrine\ORM\EntityRepository
{

	public function getNouveauxDossiersActualises($from_fr , $to_fr)
    {
    	$from_us = date('Y-m-d 00:00:00', strtotime(str_replace('/', '-', $from_fr)));
        $to_us = date('Y-m-d 23:59:59', strtotime(str_replace('/', '-', $to_fr)));

        $qb = $this->createQueryBuilder('Piece');
        $query = $qb->leftJoin('Piece.Dossier', 'Dossier')
            ->addSelect('Dossier')
            ->where('Piece.date BETWEEN :from AND :to')
            ->setParameter('from',$from_us)
            ->setParameter('to',$to_us)
            ->getQuery();

        return $query->getResult();
    }

}
