<?php

namespace FadcoBundle\Repository;

/**
 * ReabonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReabonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
