<?php

namespace LCBundle\Entity;

/**
 * DernierMessageLuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DernierMessageLuRepository extends \Doctrine\ORM\EntityRepository
{

	public function getByUserAndDiscussion($user, $disc){

		$qb = $this->createQueryBuilder('dml');
		$qb->where('dml.user = :u')
		->setParameter('u', $user)
		->andWhere('dml.discussion = :d')
		->setParameter('d', $disc);
		
		return $qb->getQuery()->getResult();
	}
}
