<?php

namespace LCBundle\Entity;

/**
 * LcDiscussionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LcDiscussionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDiscussionEntre($user, $userAvec){

	$qb = $this->createQueryBuilder('d');
	$qb->where("d.adeux = :a")
        ->setParameter('a', $user.",".$userAvec)
        ->orWhere("d.adeux = :b")
        ->setParameter('b', $userAvec.",".$user);
		
	return $qb->getQuery()->getResult();
    }
}
