<?php

namespace LCBundle\Entity;

/**
 * LcMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LcMessageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDiscussionNouveauxMessages($dml){
		$qb = $this->createQueryBuilder('lcm');
		$qb->where('lcm.date > :dte')
		->setParameter('dte', $dml->getMessage()->getDate())
		->andWhere('lcm.discussion = :disc')
		->setParameter('disc', $dml->getDiscussion());
		
		return $qb->getQuery()->getResult();
	}


	public function getDiscussionAncienMessages($dml){
		$qb = $this->createQueryBuilder('lcm');
		$qb->where('lcm.date <= :dte')
		->setParameter('dte', $dml->getMessage()->getDate())
		->andWhere('lcm.discussion = :disc')
		->setParameter('disc', $dml->getDiscussion());
		
		return $qb->getQuery()->getResult();
	}
}
