<?php

namespace FadcoBundle\Controller\DataTable\DataTable\Ajax\Repository;

/**
 * DataTableAjax
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataTableAjaxRepository extends \Doctrine\ORM\EntityRepository
{

}
