fadco_espace_distributeur:
    path:     /
    defaults: { _controller: FadcoBundle:Distributeur:index }

# reabo. direct

fadco_espace_distributeur_reabo:
    path:     /liste-reabonnements
    defaults: { _controller: FadcoBundle:Distributeur:indexReabo }

fadco_espace_distributeur_reabo_new:
    path:     /nouveau-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:newReabo }
    methods: [GET, POST]

fadco_espace_distributeur_reabo_show:
    path:     /{id}/consulter-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:showReabo }

fadco_espace_distributeur_reabo_valider:
    path:     /{id}/valider-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:validerReabo }
    methods: [GET, POST]

fadco_espace_distributeur_reabo_new_confirm:
    path:     /confirm-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:newReaboConfirm }

fadco_espace_distributeur_reabo_renew:
    path:     /{id}/renouveller-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:renewReabo }

fadco_espace_distributeur_reabo_ancien_abonne_infos:
    path: /infos-ancien-abonne
    defaults: {_controller: "FadcoBundle:Distributeur:ancienAbonneReabo"}

# reparation et installation

fadco_espace_distributeur_repair:
    path:     /liste-prestations
    defaults: { _controller: FadcoBundle:Distributeur:indexRepair }

fadco_espace_distributeur_repair_new:
    path:     /nouvelle-prestation
    defaults: { _controller: FadcoBundle:Distributeur:newRepair }
    methods: [GET, POST]

fadco_espace_distributeur_repair_new_client:
    path:     /nouveau-client
    defaults: { _controller: FadcoBundle:Distributeur:newClient }
    methods: [GET, POST]

# complements
fadco_espace_distributeur_reabo_complement:
    path:     /liste-complements
    defaults: { _controller: FadcoBundle:Distributeur:indexReaboComplement }

fadco_espace_distributeur_reabo_complement_new:
    path:     /nouveau-complement
    defaults: { _controller: FadcoBundle:Distributeur:newReaboComplement }
    methods: [GET, POST]

fadco_espace_distributeur_reabo_complement_show:
    path:     /{id}/consulter-complement
    defaults: { _controller: FadcoBundle:Distributeur:showReaboComplement }

fadco_espace_distributeur_reabo_ancien_reabo_infos:
    path: /infos-ancien-reabo
    defaults: {_controller: "FadcoBundle:Distributeur:ancienReabo"}

fadco_espace_distributeur_reabo_complement_new_confirm:
    path:     /confirm-complement
    defaults: { _controller: FadcoBundle:Distributeur:newReaboComplementConfirm }

fadco_espace_distributeur_reabo_complement_valider:
    path:     /{id}/valider-complement
    defaults: { _controller: FadcoBundle:Distributeur:validerReaboComplement }
    methods: [GET, POST]