fadco_espace_distributeur:
    path:     /
    defaults: { _controller: FadcoBundle:Distributeur:index }

# reabo. direct

fadco_espace_distributeur_reabo:
    path:     /liste-reabonnements
    defaults: { _controller: FadcoBundle:Distributeur:indexReabo }

fadco_espace_distributeur_reabo_new:
    path:     /nouveau-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:newReabo }
    methods: [GET, POST]

fadco_espace_distributeur_reabo_new_confirm:
    path:     /confirm-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:newReaboConfirm }

fadco_espace_distributeur_reabo_renew:
    path:     /{id}/renouveller-reabonnement
    defaults: { _controller: FadcoBundle:Distributeur:renewReabo }

fadco_espace_distributeur_reabo_ancien_abonne_infos:
    path: /infos-ancien-abonne
    defaults: {_controller: "FadcoBundle:Distributeur:ancienAbonneReabo"}

# reparation et installation

fadco_espace_distributeur_repair:
    path:     /liste-prestations
    defaults: { _controller: FadcoBundle:Distributeur:indexRepair }

fadco_espace_distributeur_repair_new:
    path:     /nouvelle-prestation
    defaults: { _controller: FadcoBundle:Distributeur:newRepair }
    methods: [GET, POST]

fadco_espace_distributeur_repair_new_client:
    path:     /nouveau-client
    defaults: { _controller: FadcoBundle:Distributeur:newClient }
    methods: [GET, POST]