fadco_indicateur_performance:
    path:     /
    defaults: { _controller: FadcoBundle:IndicateurPerformance:index }

fadco_indicateur_performance_nombre_visited_client:
    path:     /nombre-visited-client 
    defaults: { _controller: FadcoBundle:IndicateurPerformance:nombreVisitedClient }

fadco_indicateur_performance_dsc:    
    path:   /dsc
    defaults: { _controller: FadcoBundle:IndicateurPerformance/DSCPerformance:index}

fadco_indicateur_performance_dai:    
    path:   /dai
    defaults: { _controller: FadcoBundle:IndicateurPerformance/DAIPerformance:index}

fadco_indicateur_performance_archives:    
    path:   /dossiers
    defaults: { _controller: FadcoBundle:IndicateurPerformance/ConsultationArchives:index}

fadco_indicateur_performance_dsav:
    path:   /dsav
    defaults: { _controller: FadcoBundle:IndicateurPerformance/DSAVPerformance:index}

fadco_indicateur_performance_dsj:
    path:   /dsj
    defaults: { _controller: FadcoBundle:IndicateurPerformance/DSJPerformance:index}

fadco_indicateur_performance_dfca:
    path:   /dfca
    defaults: { _controller: FadcoBundle:IndicateurPerformance/DFCAPerformance:index}