archive_dossier_piece:
    path:     /
    defaults: { _controller: "FadcoBundle:Piece:index" }

archive_dossier_piece_show:
    path:     /{id}/show
    defaults: { _controller: "FadcoBundle:Piece:show" }

archive_dossier_piece_new:
    path:     /new
    defaults: { _controller: "FadcoBundle:Piece:new" }

archive_dossier_piece_create:
    path:     /create
    defaults: { _controller: "FadcoBundle:Piece:create" }
    methods:  POST

archive_dossier_piece_edit:
    path:     /{id}/edit
    defaults: { _controller: "FadcoBundle:Piece:edit" }

archive_dossier_piece_update:
    path:     /{id}/update
    defaults: { _controller: "FadcoBundle:Piece:update" }
    methods:  [POST, PUT]

archive_dossier_piece_delete:
    path:     /{id}/delete
    defaults: { _controller: "FadcoBundle:Piece:delete" }
    methods:  [POST, DELETE]

demande_dossier_piece:
    path:     /show
    defaults: { _controller: "FadcoBundle:Piece:indexPiece" }
