grh_prestataire:
    path:     /
    defaults: { _controller: "FadcoBundle:Prestataire:index" }

grh_prestataire_voir:
    path:     /{id}/voir
    defaults: { _controller: "FadcoBundle:Prestataire:voir" }

grh_prestataire_active:
    path:     /{id}/active
    defaults: { _controller: "FadcoBundle:Prestataire:active" }

grh_prestataire_desactive:
    path:     /{id}/desactive
    defaults: { _controller: "FadcoBundle:Prestataire:desactive" }

grh_prestataire_show:
    path:      /show
    defaults: { _controller: "FadcoBundle:Prestataire:show" }

crediter_compte_distributeur:
    path:      /distributeur-{id}
    defaults: { _controller: "FadcoBundle:Prestataire:creditAccount" }

grh_prestataire_edit:
    path:     /edit
    defaults: { _controller: "FadcoBundle:Prestataire:edit" }
    
grh_prestataire_change_password:
    path:   /change/password
    defaults: { _controller: "FadcoBundle:Prestataire:changePassword" }
    
grh_prestataire_change:
    path:   /change
    defaults: { _controller: "FadcoBundle:Prestataire:change" }

grh_prestataire_new:
    path:     /new/{id}
    defaults: { _controller: "FadcoBundle:Prestataire:edit", id = null }

grh_prestataire_update:
    path:     /update/{id}
    defaults: { _controller: "FadcoBundle:Prestataire:update", id = null }
    methods: [POST]

grh_prestataire_modifier_profile:
   path: /aller/modifier/profile
   defaults: {_controller: "FadcoBundle:Prestataire:modifierProfile"}

grh_prestataire_modifier_profile_photo:
   path: /photo/prestataire/update
   defaults: {_controller: "FadcoBundle:Prestataire:photoPrestataire"}

grh_prestataire_get_prestataire_enabled:
   path: /prestataire/enabled
   defaults: {_controller: "FadcoBundle:Prestataire:getPrestataireEnabled"}